Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: pjserrano.auth.infrastructure.adapter.in.web.AuthLambdaHandler::handleRequest
      CodeUri: C:\Users\pserranc\IdeaProjects\MyServerlessApp\login-module
      Runtime: java21
      Architectures:
        - x86_64