Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: pjserrano.auth.AuthLambdaHandler::handleRequest
      CodeUri: C:\Users\pserranc\IdeaProjects\MyServerlessApp\auth-module
      Runtime: java21
      Architectures:
        - x86_64