Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: C:\Users\pserranc\IdeaProjects\MyServerlessApp\HelloWorldFunction
      Runtime: java21
      Architectures:
        - x86_64