AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth Module Serverless Application

Globals:
  Function:
    Timeout: 30 # Default timeout for all functions

Resources:
  AuthLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.pjserrano.auth.infrastructure.adapter.in.web.AuthLambdaHandler::handleRequest # ¡MUY IMPORTANTE! Tu Handler
      Runtime: java21
      CodeUri: auth-module # Esto apunta a la carpeta del módulo
      MemorySize: 128
      Architectures:
        - x86_64
      Events:
        AuthApi:
          Type: Api
          Properties:
            Path: /auth/login # La ruta para tu Lambda de login
            Method: post