AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MyServerlessApp - Login Module using an existing secret from Parameter Store.

Globals:
  Function:
    Runtime: java21
    MemorySize: 512
    Timeout: 30
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    # Configuración de SnapStart: activa SnapStart para todas las funciones
    SnapStart:
      ApplyOn: PublishedVersions

Resources:
  # Define la tabla de DynamoDB
  LoginUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Define la función Lambda
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Esto cambiará más adelante para referenciar a una variable de maven, de forma que al ejecutar
      # sam build para el despliegue, y SAM llame a maven para el build del modulo, inyecte el nombre
      # correcto del jar
      # CodeUri: target/${CodeUriJarName}
      CodeUri: target/login-1.0.0.jar
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: loginFunction
          # Inyecta el secreto como variable de entorno desde Parameter Store
          # ¡Asume que este parámetro ya existe en AWS!
          jwt.secret: "{{resolve:ssm:/login/jwt/secret}}"
          jwt.expiration: "3600000"
      Policies:
        # Permisos a la Lambda para leer el parámetro
        - SSMParameterReadPolicy:
            ParameterName: "/login/jwt/secret"
        # Permisos de lectura a la tabla de DynamoDB
        - DynamoDBCrudPolicy:
            TableName: !Ref LoginUsersTable
      Events:
        LoginApi:
          Type: HttpApi
          Properties:
            Path: /login
            Method: POST

Outputs:
  LoginApiUrl:
    Description: "API Gateway endpoint URL for Login Function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/login"

  LoginUsersTableArn:
    Description: "ARN of the DynamoDB users table"
    Value: !GetAtt LoginUsersTable.Arn
