name: CI de auth-manager
on:
  push:
    branches:
      - develop
      - master
      - 'feature/**'
    paths:
      - 'auth-manager/**'
      - 'pom.xml'
  pull_request:
    branches:
      - develop
      - master
      - 'feature/**'
    paths:
      - 'auth-manager/**'
      - 'pom.xml'

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      module_name: 'auth-manager'