name: auth-manager-CI

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'auth-manager/**'
      - 'pom.xml'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - 'auth-manager/**'
      - 'pom.xml'

  workflow_dispatch:

jobs:
  build-and-test-and-sonar:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'maven'

      - name: Configurar credenciales de Maven para GitHub Packages
        shell: bash
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Ejecutar Tests Unitarios
        run: |
          # Solo tests unitarios (rápidos, sin dependencias externas)
          cd auth-manager
          mvn -B clean test -Dtest="**/*UnitTest"
          
      - name: Compilar artefactos
        run: |
          # Compilar sin ejecutar tests (ya ejecutados arriba)
          cd auth-manager
          mvn -B compile package -DskipTests

      - name: Subir Informes de Pruebas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: 'auth-manager/**/target/surefire-reports'

      - name: Subir artefactos de build
        run: |
          cd auth-manager
          mvn -B deploy -s settings.xml