name: Limpiar versiones de paquetes

on:
  schedule:
    # Se ejecuta todos los días a la medianoche (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Nombre del paquete a limpiar'
        required: true
        default: 'pjserrano.auth-manager'

jobs:
  delete-old-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Instalar gh (GitHub CLI)
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Borrar versiones antiguas de SNAPSHOT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener el nombre del paquete del input o usar el valor por defecto
          PACKAGE_NAME="${{ github.event.inputs.package_name || 'pjserrano.auth-manager' }}"

          # Obtener la lista de versiones del paquete.
          # Nota: La API devuelve la más reciente primero.
          versions=$(gh api "users/${{ github.actor }}/packages/maven/${PACKAGE_NAME}/versions" --jq '.[].id')
          
          if [ -z "$versions" ]; then
            echo "No se encontraron versiones para eliminar."
            exit 0
          fi
          
          # Separar la lista por líneas
          version_ids=($versions)
          
          # Si hay solo una versión o menos, no hacemos nada
          if [ "${#version_ids[@]}" -le 1 ]; then
            echo "Hay una sola versión, no se borra nada."
            exit 0
          fi
          
          # Mantener solo la última versión (la más reciente, que está en la posición 0)
          version_to_keep=${version_ids[0]}
          echo "Se mantendrá la versión más reciente: $version_to_keep"

          # Iterar sobre el resto de las versiones y eliminarlas
          for id in "${version_ids[@]:1}"; do
            echo "Borrando versión $id..."
            gh api "users/${{ github.actor }}/packages/maven/${PACKAGE_NAME}/versions/$id" -X DELETE
          done
          
          echo "Proceso de limpieza completado. Se han eliminado todas las versiones excepto la más reciente."