name: Manual Release with POM Version

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Nombre del módulo a desplegar'
        required: true
        type: choice
        options:
          - auth-manager
          - user-manager

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Inject GitHub SSL Certificate
        run: |
          # Descarga el certificado de GitHub y lo añade al cacerts de Java
          echo | openssl s_client -connect maven.pkg.github.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/github.pem
          keytool -import -trustcacerts -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -alias github-cert -file /tmp/github.pem
          
      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Extract version from POM
        id: get_version
        run: |
          MODULE_NAME="${{ github.event.inputs.module }}"
          VERSION=$(mvn -f "${MODULE_NAME}/pom.xml" help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "module_version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Packages
        run: |
          mvn deploy -f "${{ github.event.inputs.module }}/pom.xml" -s ~/.m2/settings.xml
      
      - name: Create release tag
        id: create_tag
        env:
          MODULE_NAME: ${{ github.event.inputs.module }}
          RELEASE_VERSION: ${{ steps.get_version.outputs.module_version }}
        run: |
          TAG_NAME="${MODULE_NAME}-${RELEASE_VERSION}"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: ${{ steps.create_tag.outputs.tag_name }}
          body: |
            🎉 Release for module ${{ github.event.inputs.module }}
            Version: ${{ steps.get_version.outputs.module_version }}
          draft: false
          prerelease: false
