name: Build, Compile, Test & SonarCloud Analysis

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-test-and-sonar:
    runs-on: ubuntu-latest
    


    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'



      - name: Ejecutar Tests Unitarios
        run: |
          # Solo tests unitarios (r치pidos, sin dependencias externas)
          mvn -B clean test -Dtest="**/*UnitTest"
          
      - name: Ejecutar Tests de Producci칩n (si hay credenciales AWS)
        if: env.AWS_REGION != ''
        run: |
          # Tests de producci칩n solo si hay configuraci칩n AWS
          mvn -B test -Dtest="**/*ProductionTest,**/DynamoDbConfigTest"
        env:
          AWS_REGION: eu-west-1
          
      - name: Compilar artefactos
        run: |
          # Compilar sin ejecutar tests (ya ejecutados arriba)
          mvn -B compile package -DskipTests

      - name: Subir Informes de Pruebas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: '**/target/surefire-reports'

      - name: Subir artefactos de build
        uses: actions/upload-artifact@v4
        with:
          name: java-artefactos-build
          path: target/*.jar