name: Build, Compile, Test & SonarCloud Analysis

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-test-and-sonar:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:24-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Verificar Docker y preparar entorno
        run: |
          docker --version
          docker info
          # Pre-pull de imágenes necesarias para tests
          docker pull localstack/localstack:latest
          # Configurar variable para tests de integración
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV
          echo "TESTCONTAINERS_HOST_OVERRIDE=localhost" >> $GITHUB_ENV

      - name: Build, Compilar y Ejecutar Pruebas con Maven
        run: |
          # Ejecutar tests con Docker disponible
          mvn -B clean package -Ddocker.available=true
        env:
          DOCKER_HOST: tcp://localhost:2375

      - name: Subir Informes de Pruebas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports
          path: '**/target/surefire-reports'

      - name: Subir artefactos de build
        uses: actions/upload-artifact@v4
        with:
          name: java-artefactos-build
          path: target/*.jar