spring:
  datasource:
    url: jdbc:mysql://<hostname>:<port>/<database_name>
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml